### ISSUE TITLE
Could not connect to "http://localhost:8000/" even when the app is running 

### ISSUE THREAD

**Issue by simonaco** [Azure/static-web-apps-cli#297]
**Describe the bug**
Swa cli fails to start with error message [swa] Could not connect to "http://localhost:8000/". Is the server up and running? after successful start of gatsby dev server

**To Reproduce**
1. Go to terminal
2. Type in command swa start http://localhost:8000/ --api http://localhost:7071 --run "npm start"
3. See error

**Expected behavior**
Expectation is that swa cli detects that gatsby has started

**Screenshots**
![Screenshot 2021-09-19 at 12 19 17](https://user-images.githubusercontent.com/1573904/133923966-485f73b2-ff61-45e7-942f-6d9f49bfde05.png)

**Comment by manekinekko** [comment]
Hey @simonaco thank you for reporting this issue. The good news is that we've already fixed it in https://github.com/Azure/static-web-apps-cli/pull/281 (issue https://github.com/Azure/static-web-apps-cli/issues/275). However, we haven't published a release to npm yet. cc @anthonychu.

Just as an FYI, here are the steps I followed (using v 0.7.2 - currently in main branch):
1. `install Gatsby: npm install -g gatsby-cli`
2. create a new blog: `gatsby new blog https://github.com/gatsbyjs/gatsby-starter-blog`
3. `cd blog`
4. `swa start http://localhost:8000 --run "npm start"` (I am not using SWA API)
5. access blog at `http://localhost:4280`
6. access GraphQL console at: http://localhost:4280/___graphql

As you can see from my screenshots
![image](https://user-images.githubusercontent.com/1699357/133926749-8a2dd867-e2d5-48ee-b9e4-3a534ff91d8a.png)

![image](https://user-images.githubusercontent.com/1699357/133926684-fa6db73c-13f4-4490-9079-57736c1ce542.png)

**Comment by Reshmi-Sriram** [comment]
Hey @simonaco, 
We have an upcoming release this week and you should see it in the latest npm package soon! 😄

**Comment by manekinekko** [comment]
This is awesome! Thank you @Reshmi-Sriram 👍

**Comment by sgollapudi77** [comment]
Hii @simonaco we've done a new release today and previous changes have been included in this, please check once.

**Comment by simonaco** [comment]
thank you @Reshmi-Sriram @sgollapudi77 . I just tested with a simple Gatsby app and one API endpoint and I'm still seeing issues, please check this screen recording [swa-cli doesn't start](https://youtu.be/X-Y1JfJMobg)

**Comment by simonaco** [comment]
Thank you @manekinekko for debugging with me. It seems like the issue was related to how I was starting the CLI. When using this command,  swa start http://localhost:8000/ --api http://localhost:7071 --run "npm start" I need to have the functions server started. 

Alternatively I can use this command to instruct the CLI to start the functions dev server: swa start http://localhost:8000/ --api api --run "npm start"
